/* Form Menu
*/
package ui;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;

public class FormMenuT extends javax.swing.JFrame {
    String user = "root";
    String pwd = "";
    String url = "jdbc:mysql://localhost:3306/penggajiandb";
    static boolean maximized = true;
    int xMouse;
    int yMouse;
    private Dimension screensize;
    
    /**
     * Creates new form FormMenu
     */
    public FormMenuT() {
        initComponents();
        screensize = Toolkit.getDefaultToolkit().getScreenSize(); 
        setLocation((screensize.width / 2) - (getSize().width / 2), (screensize.height / 2) - (getSize().height / 2));
    }
    
    //Method
    void today(){      
        Date ys=new Date();   
        SimpleDateFormat s=new SimpleDateFormat ("dd-MM-yyyy");
        SimpleDateFormat c=new SimpleDateFormat ("hh:mm:ss a");
        tanggal.setText(s.format(ys));
        waktu.setText(c.format(ys));
    }
    //Tabel Karyawan
    void tabelK(){    
        String[] columnNames={"ID User","Nama","Jenis Kelamin","ID Jabatan","Kontak","Alamat"};   
        JTable table=new JTable(getDataK(),columnNames);  
        table.setEnabled(false);
        karyawanPN.setViewportView(table);
    }
    private Object[][] getDataK(){   
        Object[][] data1=null;    
        try{           
            Connection conn=DriverManager.getConnection(url,user,pwd);          
            Statement st=conn.createStatement();    
            ResultSet rs=st.executeQuery("SELECT * FROM karyawan");  
            rs.last();        
            int rowCount=rs.getRow();      
            rs.beforeFirst();         
            data1=new Object[rowCount][6];       
            int no=-1;        
            while(rs.next()){         
                no=no+1;          
                data1[no][0]=rs.getString("id_user");           
                data1[no][1]=rs.getString("nama");           
                data1[no][2]=rs.getString("jenis_kelamin");     
                data1[no][3]=rs.getString("id_jabatan");
                data1[no][4]=rs.getString("kontak");
                data1[no][5]=rs.getString("alamat");
            }          
        }catch(SQLException e){      
            System.out.println("Koneksi Gagal"+e.toString());     
        } 
        return data1;   
    }
    //Tabel Jabatan
    void tabelJ(){    
        String[] columnNames={"ID Jabatan","Nama Jabatan","Gaji Pokok","Deskripsi"};   
        JTable table=new JTable(getDataJ(),columnNames);  
        table.setEnabled(false);       
        jabatanPN.setViewportView(table);   
    }
    private Object[][] getDataJ(){   
        Object[][] data1=null;    
        try{           
            Connection conn=DriverManager.getConnection(url,user,pwd);          
            Statement st=conn.createStatement();    
            ResultSet rs=st.executeQuery("SELECT * FROM jabatan");  
            rs.last();        
            int rowCount=rs.getRow();      
            rs.beforeFirst();         
            data1=new Object[rowCount][4];       
            int no=-1;        
            while(rs.next()){         
                no=no+1;          
                data1[no][0]=rs.getString("id_jabatan");           
                data1[no][1]=rs.getString("nama_jabatan");           
                data1[no][2]=rs.getString("gaji_pokok");     
                data1[no][3]=rs.getString("deskripsi");         
            }          
        }catch(SQLException e){      
            System.out.println("Koneksi Gagal"+e.toString());     
        } 
        return data1;   
    }
    
    //Getter
    public JLabel getNm_user() {
        return nm_user;
    }
    public JLabel getId_user() {
        return id_user;
    }
    public JLabel getJbt_user() {
        return jbt_user;
    }
    public JLabel getStatus() {
        return status;
    }
    public JButton getEjabatanBT() {
        return ejabatanBT;
    }
    public JButton getEkaryawanBT() {
        return ekaryawanBT;
    }
    public JButton getEuserBT() {
        return euserBT;
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new keeptoo.KGradientPanel();
        titlePN = new javax.swing.JPanel();
        closeBT = new javax.swing.JButton();
        miniBT = new javax.swing.JButton();
        upPN = new javax.swing.JPanel();
        pp = new javax.swing.JLabel();
        id_user = new javax.swing.JLabel();
        jbt_user = new javax.swing.JLabel();
        nm_user = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        succes = new javax.swing.JLabel();
        youlog = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        sidePN = new javax.swing.JPanel();
        menuIC = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        homeBT = new javax.swing.JButton();
        karyawanBT = new javax.swing.JButton();
        jabatanBT = new javax.swing.JButton();
        editBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();
        mainPN = new javax.swing.JPanel();
        homePN = new javax.swing.JPanel();
        about = new javax.swing.JPanel();
        titleabout = new javax.swing.JTextField();
        L1 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L22 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L33 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        bsiabout = new javax.swing.JTextField();
        gajiBT = new javax.swing.JButton();
        gaji_id = new javax.swing.JTextField();
        gaji_nama = new javax.swing.JTextField();
        gaji_nilai = new javax.swing.JTextField();
        karyawanPN = new javax.swing.JScrollPane();
        karyawanTB = new javax.swing.JTable();
        jabatanPN = new javax.swing.JScrollPane();
        jabatanTB = new javax.swing.JTable();
        editPN = new javax.swing.JPanel();
        ekaryawanPN = new javax.swing.JPanel();
        karyawanGB = new javax.swing.JLabel();
        ekaryawanBT = new javax.swing.JButton();
        ejabatanPN = new javax.swing.JPanel();
        jabatanGB = new javax.swing.JLabel();
        ejabatanBT = new javax.swing.JButton();
        epassPN = new javax.swing.JPanel();
        epassIC = new javax.swing.JLabel();
        epassBT = new javax.swing.JButton();
        euserPN = new javax.swing.JPanel();
        euserIC = new javax.swing.JLabel();
        euserBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        bg.setkEndColor(new java.awt.Color(0, 51, 153));
        bg.setkGradientFocus(250);
        bg.setkStartColor(new java.awt.Color(0, 102, 0));

        titlePN.setBackground(new java.awt.Color(255, 255, 255));
        titlePN.setMaximumSize(new java.awt.Dimension(800, 25));
        titlePN.setMinimumSize(new java.awt.Dimension(800, 25));
        titlePN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlePNMouseDragged(evt);
            }
        });
        titlePN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlePNMousePressed(evt);
            }
        });

        closeBT.setBackground(new java.awt.Color(255, 0, 0));
        closeBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/closeBT.png"))); // NOI18N
        closeBT.setContentAreaFilled(false);
        closeBT.setOpaque(true);
        closeBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBTMouseExited(evt);
            }
        });
        closeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTActionPerformed(evt);
            }
        });

        miniBT.setBackground(new java.awt.Color(255, 255, 255));
        miniBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/miniBT.png"))); // NOI18N
        miniBT.setContentAreaFilled(false);
        miniBT.setOpaque(true);
        miniBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniBTMouseExited(evt);
            }
        });
        miniBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titlePNLayout = new javax.swing.GroupLayout(titlePN);
        titlePN.setLayout(titlePNLayout);
        titlePNLayout.setHorizontalGroup(
            titlePNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePNLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(miniBT)
                .addGap(0, 0, 0)
                .addComponent(closeBT))
        );
        titlePNLayout.setVerticalGroup(
            titlePNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeBT)
            .addComponent(miniBT)
        );

        upPN.setBackground(new java.awt.Color(255, 255, 255));
        upPN.setMaximumSize(new java.awt.Dimension(54, 150));
        upPN.setMinimumSize(new java.awt.Dimension(54, 150));
        upPN.setPreferredSize(new java.awt.Dimension(54, 150));

        pp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png"))); // NOI18N

        id_user.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_user.setText("ID User");

        jbt_user.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbt_user.setText("Jabatan");

        nm_user.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        nm_user.setText("Nama User");

        tanggal.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tanggal.setText("Tanggal");

        waktu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        waktu.setText("Waktu");

        succes.setText("succesfull login at:");

        youlog.setText("You are login as");

        status.setText("status,");

        javax.swing.GroupLayout upPNLayout = new javax.swing.GroupLayout(upPN);
        upPN.setLayout(upPNLayout);
        upPNLayout.setHorizontalGroup(
            upPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upPNLayout.createSequentialGroup()
                .addGroup(upPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(upPNLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(pp)
                        .addGap(46, 46, 46)
                        .addGroup(upPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_user, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nm_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbt_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(upPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(waktu, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upPNLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(youlog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(succes)))
                .addContainerGap())
        );
        upPNLayout.setVerticalGroup(
            upPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upPNLayout.createSequentialGroup()
                .addGroup(upPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(succes)
                    .addComponent(status)
                    .addComponent(youlog))
                .addGap(11, 11, 11)
                .addGroup(upPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(upPNLayout.createSequentialGroup()
                        .addComponent(nm_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt_user))
                    .addGroup(upPNLayout.createSequentialGroup()
                        .addGroup(upPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pp)
                            .addGroup(upPNLayout.createSequentialGroup()
                                .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(waktu)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(125, 125, 125))
        );

        sidePN.setBackground(new java.awt.Color(51, 51, 51));

        menuIC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N

        menu.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setText("MENU");

        homeBT.setBackground(new java.awt.Color(51, 51, 51));
        homeBT.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        homeBT.setForeground(new java.awt.Color(255, 255, 255));
        homeBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        homeBT.setText("HOME");
        homeBT.setContentAreaFilled(false);
        homeBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBT.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        homeBT.setOpaque(true);
        homeBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBTMouseExited(evt);
            }
        });
        homeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTActionPerformed(evt);
            }
        });

        karyawanBT.setBackground(new java.awt.Color(51, 51, 51));
        karyawanBT.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        karyawanBT.setForeground(new java.awt.Color(255, 255, 255));
        karyawanBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/karyawan.png"))); // NOI18N
        karyawanBT.setText("DATA KARYAWAN");
        karyawanBT.setContentAreaFilled(false);
        karyawanBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        karyawanBT.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        karyawanBT.setOpaque(true);
        karyawanBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                karyawanBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                karyawanBTMouseExited(evt);
            }
        });
        karyawanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanBTActionPerformed(evt);
            }
        });

        jabatanBT.setBackground(new java.awt.Color(51, 51, 51));
        jabatanBT.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jabatanBT.setForeground(new java.awt.Color(255, 255, 255));
        jabatanBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/jabatan.png"))); // NOI18N
        jabatanBT.setText("DATA JABATAN");
        jabatanBT.setContentAreaFilled(false);
        jabatanBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jabatanBT.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jabatanBT.setOpaque(true);
        jabatanBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jabatanBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jabatanBTMouseExited(evt);
            }
        });
        jabatanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanBTActionPerformed(evt);
            }
        });

        editBT.setBackground(new java.awt.Color(51, 51, 51));
        editBT.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        editBT.setForeground(new java.awt.Color(255, 255, 255));
        editBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        editBT.setText("EDIT");
        editBT.setContentAreaFilled(false);
        editBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBT.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        editBT.setOpaque(true);
        editBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editBTMouseExited(evt);
            }
        });
        editBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTActionPerformed(evt);
            }
        });

        logoutBT.setBackground(new java.awt.Color(255, 0, 0));
        logoutBT.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        logoutBT.setForeground(new java.awt.Color(255, 255, 255));
        logoutBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        logoutBT.setText("LOGOUT");
        logoutBT.setContentAreaFilled(false);
        logoutBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBT.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        logoutBT.setOpaque(true);
        logoutBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBTMouseExited(evt);
            }
        });
        logoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePNLayout = new javax.swing.GroupLayout(sidePN);
        sidePN.setLayout(sidePNLayout);
        sidePNLayout.setHorizontalGroup(
            sidePNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuIC, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(logoutBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(karyawanBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jabatanBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(editBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePNLayout.setVerticalGroup(
            sidePNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuIC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu)
                .addGap(16, 16, 16)
                .addComponent(homeBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(karyawanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jabatanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(editBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(logoutBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        mainPN.setBackground(new java.awt.Color(255, 255, 255));
        mainPN.setMaximumSize(new java.awt.Dimension(569, 402));
        mainPN.setMinimumSize(new java.awt.Dimension(569, 402));
        mainPN.setLayout(new java.awt.CardLayout());

        homePN.setBackground(new java.awt.Color(255, 255, 255));
        homePN.setMaximumSize(new java.awt.Dimension(569, 402));
        homePN.setMinimumSize(new java.awt.Dimension(569, 402));

        about.setBackground(new java.awt.Color(255, 255, 255));
        about.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TENTANG APLIKASI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12))); // NOI18N

        titleabout.setEditable(false);
        titleabout.setBackground(new java.awt.Color(255, 255, 255));
        titleabout.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        titleabout.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        titleabout.setText("APLIKASI GAJI KARYAWAN");
        titleabout.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        titleabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleaboutActionPerformed(evt);
            }
        });

        L1.setText("Lead Programming");

        L11.setText(": MOCHAMMAD NAFISA CHAFITH");

        L2.setText("Application Design");

        L22.setText(": MOCHAMMAD NAFISA CHAFITH");

        L3.setText("Database Administrator");

        L33.setText(": MOCHAMMAD NAFISA CHAFITH");

        L4.setText("Dibuat untuk memenuhi tugas UAS 4 MATA KULIAH.");

        L5.setText("SISTEM INFORMASI 2A");

        bsiabout.setEditable(false);
        bsiabout.setBackground(new java.awt.Color(255, 255, 255));
        bsiabout.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bsiabout.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bsiabout.setText("UNIVERSITAS BRAWIJAYA MALANG");
        bsiabout.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout aboutLayout = new javax.swing.GroupLayout(about);
        about.setLayout(aboutLayout);
        aboutLayout.setHorizontalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleabout)
                    .addGroup(aboutLayout.createSequentialGroup()
                        .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aboutLayout.createSequentialGroup()
                                .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L1)
                                    .addComponent(L2)
                                    .addComponent(L3))
                                .addGap(53, 53, 53)
                                .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L33)
                                    .addComponent(L22)
                                    .addComponent(L11)))
                            .addGroup(aboutLayout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(L5)))
                        .addGap(0, 136, Short.MAX_VALUE))
                    .addComponent(bsiabout))
                .addContainerGap())
            .addGroup(aboutLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(L4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        aboutLayout.setVerticalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleabout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L1)
                    .addComponent(L11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L2)
                    .addComponent(L22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L3)
                    .addComponent(L33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bsiabout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        gajiBT.setBackground(new java.awt.Color(255, 255, 255));
        gajiBT.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        gajiBT.setForeground(new java.awt.Color(0, 153, 51));
        gajiBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ico2_48.png"))); // NOI18N
        gajiBT.setText("HITUNG GAJI");
        gajiBT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 5));
        gajiBT.setContentAreaFilled(false);
        gajiBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gajiBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gajiBT.setOpaque(true);
        gajiBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        gaji_id.setEditable(false);
        gaji_id.setBackground(new java.awt.Color(255, 255, 255));
        gaji_id.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        gaji_id.setForeground(new java.awt.Color(0, 153, 51));
        gaji_id.setText("ID Jabatan");
        gaji_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 255)));
        gaji_id.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        gaji_id.setSelectionColor(new java.awt.Color(102, 102, 255));

        gaji_nama.setEditable(false);
        gaji_nama.setBackground(new java.awt.Color(255, 255, 255));
        gaji_nama.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        gaji_nama.setForeground(new java.awt.Color(0, 153, 51));
        gaji_nama.setText("Nama Jabatan");
        gaji_nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 255)));
        gaji_nama.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        gaji_nama.setSelectionColor(new java.awt.Color(102, 102, 255));

        gaji_nilai.setEditable(false);
        gaji_nilai.setBackground(new java.awt.Color(255, 255, 255));
        gaji_nilai.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        gaji_nilai.setForeground(new java.awt.Color(0, 153, 51));
        gaji_nilai.setText("Gaji Pokok Anda");
        gaji_nilai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 255)));
        gaji_nilai.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        gaji_nilai.setSelectionColor(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout homePNLayout = new javax.swing.GroupLayout(homePN);
        homePN.setLayout(homePNLayout);
        homePNLayout.setHorizontalGroup(
            homePNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(about, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(homePNLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(homePNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(homePNLayout.createSequentialGroup()
                                .addComponent(gaji_id, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gaji_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(gaji_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(gajiBT, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        homePNLayout.setVerticalGroup(
            homePNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePNLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(homePNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(homePNLayout.createSequentialGroup()
                        .addGroup(homePNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(gaji_id)
                            .addComponent(gaji_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gaji_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(gajiBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        mainPN.add(homePN, "card2");

        karyawanPN.setMaximumSize(new java.awt.Dimension(569, 402));
        karyawanPN.setMinimumSize(new java.awt.Dimension(569, 402));
        karyawanPN.setPreferredSize(new java.awt.Dimension(569, 402));

        karyawanTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tabel Karyawan"
            }
        ));
        karyawanPN.setViewportView(karyawanTB);

        mainPN.add(karyawanPN, "card3");

        jabatanPN.setMaximumSize(new java.awt.Dimension(569, 402));
        jabatanPN.setMinimumSize(new java.awt.Dimension(569, 402));
        jabatanPN.setPreferredSize(new java.awt.Dimension(569, 402));

        jabatanTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tabel Jabatan"
            }
        ));
        jabatanPN.setViewportView(jabatanTB);

        mainPN.add(jabatanPN, "card4");

        editPN.setBackground(new java.awt.Color(255, 255, 255));
        editPN.setMaximumSize(new java.awt.Dimension(569, 402));
        editPN.setMinimumSize(new java.awt.Dimension(569, 402));

        ekaryawanPN.setBackground(new java.awt.Color(255, 255, 255));

        karyawanGB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/kar.jpg"))); // NOI18N

        javax.swing.GroupLayout ekaryawanPNLayout = new javax.swing.GroupLayout(ekaryawanPN);
        ekaryawanPN.setLayout(ekaryawanPNLayout);
        ekaryawanPNLayout.setHorizontalGroup(
            ekaryawanPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(karyawanGB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ekaryawanPNLayout.setVerticalGroup(
            ekaryawanPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(karyawanGB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ekaryawanBT.setBackground(new java.awt.Color(0, 153, 204));
        ekaryawanBT.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        ekaryawanBT.setForeground(new java.awt.Color(255, 255, 255));
        ekaryawanBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ekaryawan.png"))); // NOI18N
        ekaryawanBT.setText("DATA KARYAWAN");
        ekaryawanBT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 0, 0)));
        ekaryawanBT.setContentAreaFilled(false);
        ekaryawanBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ekaryawanBT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ekaryawanBT.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ekaryawanBT.setOpaque(true);
        ekaryawanBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ekaryawanBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ekaryawanBTMouseExited(evt);
            }
        });
        ekaryawanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekaryawanBTActionPerformed(evt);
            }
        });

        ejabatanPN.setBackground(new java.awt.Color(255, 255, 255));

        jabatanGB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/jab.jpg"))); // NOI18N

        javax.swing.GroupLayout ejabatanPNLayout = new javax.swing.GroupLayout(ejabatanPN);
        ejabatanPN.setLayout(ejabatanPNLayout);
        ejabatanPNLayout.setHorizontalGroup(
            ejabatanPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jabatanGB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ejabatanPNLayout.setVerticalGroup(
            ejabatanPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jabatanGB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ejabatanBT.setBackground(new java.awt.Color(0, 153, 204));
        ejabatanBT.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        ejabatanBT.setForeground(new java.awt.Color(255, 255, 255));
        ejabatanBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ejabatan.png"))); // NOI18N
        ejabatanBT.setText("DATA JABATAN");
        ejabatanBT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 0, 0)));
        ejabatanBT.setContentAreaFilled(false);
        ejabatanBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ejabatanBT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ejabatanBT.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ejabatanBT.setOpaque(true);
        ejabatanBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ejabatanBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ejabatanBTMouseExited(evt);
            }
        });
        ejabatanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejabatanBTActionPerformed(evt);
            }
        });

        epassPN.setBackground(new java.awt.Color(255, 255, 255));

        epassIC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        epassIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/epassb.png"))); // NOI18N
        epassIC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout epassPNLayout = new javax.swing.GroupLayout(epassPN);
        epassPN.setLayout(epassPNLayout);
        epassPNLayout.setHorizontalGroup(
            epassPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(epassIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        epassPNLayout.setVerticalGroup(
            epassPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(epassIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        epassBT.setBackground(new java.awt.Color(0, 0, 0));
        epassBT.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        epassBT.setForeground(new java.awt.Color(255, 255, 255));
        epassBT.setText("UBAH PASSWORD");
        epassBT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 102, 0)));
        epassBT.setContentAreaFilled(false);
        epassBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        epassBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        epassBT.setOpaque(true);
        epassBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        epassBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                epassBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                epassBTMouseExited(evt);
            }
        });
        epassBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epassBTActionPerformed(evt);
            }
        });

        euserPN.setBackground(new java.awt.Color(255, 255, 255));

        euserIC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        euserIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/epenggunab.png"))); // NOI18N
        euserIC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout euserPNLayout = new javax.swing.GroupLayout(euserPN);
        euserPN.setLayout(euserPNLayout);
        euserPNLayout.setHorizontalGroup(
            euserPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(euserIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        euserPNLayout.setVerticalGroup(
            euserPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(euserPNLayout.createSequentialGroup()
                .addComponent(euserIC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        euserBT.setBackground(new java.awt.Color(0, 0, 0));
        euserBT.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        euserBT.setForeground(new java.awt.Color(255, 255, 255));
        euserBT.setText("DATA PENGGUNA");
        euserBT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 102, 0)));
        euserBT.setContentAreaFilled(false);
        euserBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        euserBT.setOpaque(true);
        euserBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                euserBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                euserBTMouseExited(evt);
            }
        });
        euserBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euserBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPNLayout = new javax.swing.GroupLayout(editPN);
        editPN.setLayout(editPNLayout);
        editPNLayout.setHorizontalGroup(
            editPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPNLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(editPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ekaryawanBT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ekaryawanPN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ejabatanPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ejabatanBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(editPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(epassPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(epassBT, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(euserPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(euserBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        editPNLayout.setVerticalGroup(
            editPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPNLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(editPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ekaryawanPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(epassPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(editPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(epassBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ekaryawanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(editPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(euserPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ejabatanPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(editPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ejabatanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(euserBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        mainPN.add(editPN, "card5");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upPN, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(sidePN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(mainPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(titlePN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(upPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidePN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPN, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titlePNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePNMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_titlePNMousePressed

    private void titlePNMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePNMouseDragged
        if(maximized){
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x - xMouse, y - yMouse);
        }
    }//GEN-LAST:event_titlePNMouseDragged

    private void closeBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBTMouseEntered
        closeBT.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_closeBTMouseEntered

    private void closeBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBTMouseExited
        closeBT.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_closeBTMouseExited

    private void closeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Keluar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {      
            System.exit(0);
        }
    }//GEN-LAST:event_closeBTActionPerformed

    private void miniBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniBTMouseEntered
        miniBT.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_miniBTMouseEntered

    private void miniBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniBTMouseExited
        miniBT.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_miniBTMouseExited

    private void miniBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniBTActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_miniBTActionPerformed

    private void homeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTActionPerformed
        mainPN.removeAll();
        mainPN.repaint();
        mainPN.revalidate();
        mainPN.add(homePN);
        mainPN.repaint();
        mainPN.revalidate();
    }//GEN-LAST:event_homeBTActionPerformed

    private void homeBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBTMouseEntered
        homeBT.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_homeBTMouseEntered

    private void homeBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBTMouseExited
        homeBT.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_homeBTMouseExited

    private void karyawanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanBTActionPerformed
        mainPN.removeAll();
        mainPN.repaint();
        mainPN.revalidate();
        mainPN.add(karyawanPN);
        mainPN.repaint();
        mainPN.revalidate();
    }//GEN-LAST:event_karyawanBTActionPerformed

    private void karyawanBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanBTMouseEntered
        karyawanBT.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_karyawanBTMouseEntered

    private void karyawanBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanBTMouseExited
        karyawanBT.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_karyawanBTMouseExited

    private void jabatanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanBTActionPerformed
        mainPN.removeAll();
        mainPN.repaint();
        mainPN.revalidate();
        mainPN.add(jabatanPN);
        mainPN.repaint();
        mainPN.revalidate();
    }//GEN-LAST:event_jabatanBTActionPerformed

    private void jabatanBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jabatanBTMouseEntered
        jabatanBT.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jabatanBTMouseEntered

    private void jabatanBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jabatanBTMouseExited
        jabatanBT.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jabatanBTMouseExited

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
        mainPN.removeAll();
        mainPN.repaint();
        mainPN.revalidate();
        mainPN.add(editPN);
        mainPN.repaint();
        mainPN.revalidate();
    }//GEN-LAST:event_editBTActionPerformed

    private void editBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBTMouseEntered
        editBT.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_editBTMouseEntered

    private void editBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBTMouseExited
        editBT.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_editBTMouseExited

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin logout?", "Logout", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {      
            this.dispose();
            FormLoginT flogin = new FormLoginT();
            flogin.setLocationRelativeTo(null);
            flogin.setVisible(true);
        }
    }//GEN-LAST:event_logoutBTActionPerformed

    private void logoutBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBTMouseEntered
        logoutBT.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_logoutBTMouseEntered

    private void logoutBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBTMouseExited
        logoutBT.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_logoutBTMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        today();
        tabelK();
        tabelJ();
    }//GEN-LAST:event_formWindowActivated

    private void ekaryawanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekaryawanBTActionPerformed
        FormEKaryawan fkaryawan = new FormEKaryawan();
        fkaryawan.setLocationRelativeTo(null);
        fkaryawan.setVisible(true);
    }//GEN-LAST:event_ekaryawanBTActionPerformed

    private void ekaryawanBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekaryawanBTMouseEntered
        ekaryawanBT.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_ekaryawanBTMouseEntered

    private void ekaryawanBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekaryawanBTMouseExited
        ekaryawanBT.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_ekaryawanBTMouseExited

    private void ejabatanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejabatanBTActionPerformed
        FormEJabatan fjabatan = new FormEJabatan();
        fjabatan.setLocationRelativeTo(null);
        fjabatan.setVisible(true);
    }//GEN-LAST:event_ejabatanBTActionPerformed

    private void ejabatanBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejabatanBTMouseEntered
        ejabatanBT.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_ejabatanBTMouseEntered

    private void ejabatanBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejabatanBTMouseExited
        ejabatanBT.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_ejabatanBTMouseExited

    private void epassBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epassBTActionPerformed
        FormEPass fpass = new FormEPass();
        fpass.setLocationRelativeTo(null);
        fpass.setVisible(true);
    }//GEN-LAST:event_epassBTActionPerformed

    private void epassBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_epassBTMouseEntered
        epassIC.setIcon(new ImageIcon(getClass().getResource("/icon/epassg.png")));
    }//GEN-LAST:event_epassBTMouseEntered

    private void epassBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_epassBTMouseExited
        epassIC.setIcon(new ImageIcon(getClass().getResource("/icon/epassb.png")));
    }//GEN-LAST:event_epassBTMouseExited

    private void euserBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euserBTActionPerformed
        FormEPengguna fuser = new FormEPengguna();
        fuser.setLocationRelativeTo(null);
        fuser.setVisible(true);
    }//GEN-LAST:event_euserBTActionPerformed

    private void euserBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_euserBTMouseEntered
        euserIC.setIcon(new ImageIcon(getClass().getResource("/icon/epenggunag.png")));
    }//GEN-LAST:event_euserBTMouseEntered

    private void euserBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_euserBTMouseExited
        euserIC.setIcon(new ImageIcon(getClass().getResource("/icon/epenggunab.png")));
    }//GEN-LAST:event_euserBTMouseExited

    private void titleaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleaboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleaboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
  
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L22;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L33;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JPanel about;
    private keeptoo.KGradientPanel bg;
    private javax.swing.JTextField bsiabout;
    private javax.swing.JButton closeBT;
    private javax.swing.JButton editBT;
    private javax.swing.JPanel editPN;
    private javax.swing.JButton ejabatanBT;
    private javax.swing.JPanel ejabatanPN;
    private javax.swing.JButton ekaryawanBT;
    private javax.swing.JPanel ekaryawanPN;
    private javax.swing.JButton epassBT;
    private javax.swing.JLabel epassIC;
    private javax.swing.JPanel epassPN;
    private javax.swing.JButton euserBT;
    private javax.swing.JLabel euserIC;
    private javax.swing.JPanel euserPN;
    private javax.swing.JButton gajiBT;
    private javax.swing.JTextField gaji_id;
    private javax.swing.JTextField gaji_nama;
    private javax.swing.JTextField gaji_nilai;
    private javax.swing.JButton homeBT;
    private javax.swing.JPanel homePN;
    private javax.swing.JLabel id_user;
    private javax.swing.JButton jabatanBT;
    private javax.swing.JLabel jabatanGB;
    private javax.swing.JScrollPane jabatanPN;
    private javax.swing.JTable jabatanTB;
    private javax.swing.JLabel jbt_user;
    private javax.swing.JButton karyawanBT;
    private javax.swing.JLabel karyawanGB;
    private javax.swing.JScrollPane karyawanPN;
    private javax.swing.JTable karyawanTB;
    private javax.swing.JButton logoutBT;
    private javax.swing.JPanel mainPN;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel menuIC;
    private javax.swing.JButton miniBT;
    private javax.swing.JLabel nm_user;
    private javax.swing.JLabel pp;
    private javax.swing.JPanel sidePN;
    private javax.swing.JLabel status;
    private javax.swing.JLabel succes;
    private javax.swing.JLabel tanggal;
    private javax.swing.JPanel titlePN;
    private javax.swing.JTextField titleabout;
    private javax.swing.JPanel upPN;
    private javax.swing.JLabel waktu;
    private javax.swing.JLabel youlog;
    // End of variables declaration//GEN-END:variables
}
